---
name: 'Meta Test'

on: 
  pull_request:
    types: [ opened, reopened, labeled ]

jobs:
  label-check:
    name: Checks if labels are used
    runs-on: ubuntu-latest
    steps: 
        #Checking out to the develop branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Has atleast one priority label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: 'priority:high, priority:low, priority:medium'

      - name: Has atleast one type label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: 'type:bug, type:change, type:documentation, type:enhancement, type:feature, type:test'
    
      - name: Has atleast one scope label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: 'scope:api, scope:cicd, scope:db, scope:ui, scope:repository'

  milestone-check:
    name: Checks if milestone is used
    runs-on: ubuntu-latest
    steps:       
      - name: Has milestone check
        if: github.event.pull_request.milestone == null
        run: |
          echo "you don't have a milestone"
          exit 1
          