---
name: 'Backend CI Tests'

on:
  workflow_call:
    inputs:
      test:
        description: 'run Jest tests'
        required: true
        type: string
    
#jobs to run for backend folder
jobs:
  build:
    name: Generate cache
    runs-on: ubuntu-latest
    steps:
        #Checking out to the develop branch
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

        #Generates the hashes for the comparison between the origin branch and the upstream development branch
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'develop'

        #Installs node.js
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

        #installs yarn
      - name: Install yarn
        run: |
          cd backend/api
          npm install yarn -g

      - name: Cache Yarn Packages
        id: cache-yarn-packages
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: yarn-packages-${{ hashFiles('**/yarn.lock') }}

        #installs the yarn lockfile
      - name: Install packages
        run: |
          cd backend/api
          yarn install --frozen-lockfile

        #run tests on Node server
      - name: Test Node Server
        if: inputs.test == 'test'
        run: |
          cd backend/api
          yarn test

      - uses: codecov/codecov-action@v3.1.0
        if: inputs.test == 'test' 
        with:
          # Organization codecov token to be placed below
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./backend/api/coverage
          