name: Full Test Coverage

on:
  push:
    branches: [develop]

jobs:
  test-all-frontend:
    uses: ./.github/workflows/FrontendCItest.yml
    with:
      test: 'all'
      
  test-all-backend:
    uses: ./.github/workflows/BackendCITest.yml
    with:
      test: 'all'