---
name: CI Tests

on: 
  pull_request:
    branches: [ main, develop]
  #manual github action trigger with choices to run individual tests
  workflow_dispatch:
    inputs:
      testchoice:
        type: choice
        description: 'Test Type'
        required: true
        options:
        - full
        - lint
        - build
        - unit
        - all

#jobs in the workflow with passed in parameters for frontend and backend code
jobs:
  test-affected-lint-frontend:
    if: ${{ github.event.inputs.testchoice == 'lint' || github.event.inputs.testchoice == 'full' || github.event.inputs.testchoice == ''}}
    uses: ./.github/workflows/FrontendCItest.yml
    with:
      test: 'affected'
      testtype: 'lint'

  test-affected-build-frontend:
    uses: ./.github/workflows/FrontendCItest.yml
    if: ${{ github.event.inputs.testchoice == 'build' || github.event.inputs.testchoice == 'full' || github.event.inputs.testchoice == ''}}
    with:
      test: 'affected'
      testtype: 'build'
  
  test-affected-unit-frontend:
    uses: ./.github/workflows/FrontendCItest.yml
    if: ${{ github.event.inputs.testchoice == 'unit' || github.event.inputs.testchoice == 'full'|| github.event.inputs.testchoice == ''}}
    with:
      test: 'affected'
      testtype: 'unit'

  # test-affected-e2e-frontend:
  #   uses: ./.github/workflows/FrontendCItest.yml
  #   if: ${{ github.event.inputs.testchoice == 'e2e' || github.event.inputs.testchoice == 'full'|| github.event.inputs.testchoice == ''}}
  #   with:
  #     test: 'affected'
  #     testtype: 'e2e'

  test-all-frontend:
    uses: ./.github/workflows/FrontendCItest.yml
    if: ${{ github.event.inputs.testchoice == 'all'}}
    with:
      test: 'all'

  test-backend:
    if: ${{ github.event.inputs.testchoice == 'unit' || github.event.inputs.testchoice == 'full' || github.event.inputs.testchoice == ''}}
    uses: ./.github/workflows/BackendCITest.yml
    with:
      test: 'test'
